In [1]:
!pip install nltk

In [2]:
import nltk

In [3]:
paragraph = '''
Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at age eight. He has reminisced about helping out after school at his father's tea stall at the Vadnagar railway station. At age 18, Modi was married to Jashodaben Chimanlal Modi, whom he abandoned soon after. He first publicly acknowledged her as his wife more than four decades later when required to do so by Indian law, but has made no contact with her since. Modi has asserted he had travelled in northern India for two years after leaving his parental home, visiting a number of religious centres, but few details of his travels have emerged. Upon his return to Gujarat in 1971, he became a full-time worker for the RSS. After the state of emergency was declared by prime minister Indira Gandhi in 1975, Modi went into hiding. The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank of general secretary.[c]

Modi was appointed Chief Minister of Gujarat in 2001 due to Keshubhai Patel's failing health and poor public image following the earthquake in Bhuj. Modi was elected to the legislative assembly soon after. His administration has been considered complicit in the 2002 Gujarat riots in which 1044 people were killed, three-quarters of whom were Muslim,[d] or otherwise criticised for its management of the crisis. A Special Investigation Team appointed by the Supreme Court of India found no evidence to initiate prosecution proceedings against Modi personally.[e] While his policies as chief minister—credited with encouraging economic growth—have received praise, his administration was criticised for failing to significantly improve health, poverty and education indices in the state.[f]

Modi led the BJP in the 2014 general election which gave the party a majority in the lower house of Indian parliament, the Lok Sabha, the first time for any single party since 1984. Modi's administration has tried to raise foreign direct investment in the Indian economy and reduced spending on healthcare, education, and social welfare programmes. Modi centralised power by abolishing the Planning Commission and replacing it with the NITI Aayog. He began a high-profile sanitation campaign, controversially initiated a demonetisation of high-denomination banknotes and a transformation of the taxation regime, and weakened or abolished environmental and labour laws. He oversaw the country's response to the COVID-19 pandemic. As Prime Minister, Modi has received consistently high approval ratings.[12][13][14]

Under Modi's tenure, India has experienced democratic backsliding.[15][16][g] Following his party's victory in the 2019 general election, his administration revoked the special status of Jammu and Kashmir, introduced the Citizenship Amendment Act and three controversial farm laws, which prompted widespread protests and sit-ins across the country, resulting in a formal repeal of the latter. Described as engineering a political realignment towards right-wing politics, Modi remains a figure of controversy domestically and internationally over his Hindu nationalist beliefs and his handling of the 2002 Gujarat riots, cited as evidence of an exclusionary social agenda.[h]
'''

In [4]:
paragraph

"\nModi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at age eight. He has reminisced about helping out after school at his father's tea stall at the Vadnagar railway station. At age 18, Modi was married to Jashodaben Chimanlal Modi, whom he abandoned soon after. He first publicly acknowledged her as his wife more than four decades later when required to do so by Indian law, but has made no contact with her since. Modi has asserted he had travelled in northern India for two years after leaving his parental home, visiting a number of religious centres, but few details of his travels have emerged. Upon his return to Gujarat in 1971, he became a full-time worker for the RSS. After the state of emergency was declared by prime minister Indira Gandhi in 1975, Modi went into hiding. The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank o

In [5]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import nltk

In [9]:
## tokenzation
nltk.download('punkt')
sentance=nltk.sent_tokenize(paragraph)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ThinkPad-T570Worksta\AppData\Roaming\nltk_dat
[nltk_data]     a...
[nltk_data]   Package punkt is already up-to-date!


In [11]:
## 
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ThinkPad-T570Worksta\AppData\Roaming\nltk_dat
[nltk_data]     a...
[nltk_data]   Package stopwords is already up-to-date!


True

In [10]:
stemmer = PorterStemmer()
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [7]:
## STEMMING
stemmer.stem('going')

'go'

In [8]:
## lemmatizer
lemmatizer.lemmatize('going')

'going'

In [14]:
## text preprocessing
## removing the all special character
## importing the regular expression
import re

corpus = []
for i in range(len(sentance)):
    review = re.sub('[^a-zA-Z]',' ',sentance[i])
    review = review.lower()
    
    corpus.append(review)

In [15]:
corpus

[' modi was born and raised in vadnagar in northeastern gujarat  where he completed his secondary education ',
 'he was introduced to the rss at age eight ',
 'he has reminisced about helping out after school at his father s tea stall at the vadnagar railway station ',
 'at age     modi was married to jashodaben chimanlal modi  whom he abandoned soon after ',
 'he first publicly acknowledged her as his wife more than four decades later when required to do so by indian law  but has made no contact with her since ',
 'modi has asserted he had travelled in northern india for two years after leaving his parental home  visiting a number of religious centres  but few details of his travels have emerged ',
 'upon his return to gujarat in       he became a full time worker for the rss ',
 'after the state of emergency was declared by prime minister indira gandhi in       modi went into hiding ',
 'the rss assigned him to the bjp in      and he held several positions within the party hierarchy 

In [16]:
## applying stemmer on entire document
for i in corpus:
    words = nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(stemmer.stem(word))

modi
born
rais
vadnagar
northeastern
gujarat
complet
secondari
educ
introduc
rss
age
eight
reminisc
help
school
father
tea
stall
vadnagar
railway
station
age
modi
marri
jashodaben
chimanl
modi
abandon
soon
first
publicli
acknowledg
wife
four
decad
later
requir
indian
law
made
contact
sinc
modi
assert
travel
northern
india
two
year
leav
parent
home
visit
number
religi
centr
detail
travel
emerg
upon
return
gujarat
becam
full
time
worker
rss
state
emerg
declar
prime
minist
indira
gandhi
modi
went
hide
rss
assign
bjp
held
sever
posit
within
parti
hierarchi
rise
rank
gener
secretari
c
modi
appoint
chief
minist
gujarat
due
keshubhai
patel
fail
health
poor
public
imag
follow
earthquak
bhuj
modi
elect
legisl
assembl
soon
administr
consid
complicit
gujarat
riot
peopl
kill
three
quarter
muslim
otherwis
criticis
manag
crisi
special
investig
team
appoint
suprem
court
india
found
evid
initi
prosecut
proceed
modi
person
e
polici
chief
minist
credit
encourag
econom
growth
receiv
prais
administr
criti

In [18]:
## applying lemmatizer on entire document
for i in corpus:
    words = nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(lemmatizer.lemmatize(word))

modi
born
raised
vadnagar
northeastern
gujarat
completed
secondary
education
introduced
r
age
eight
reminisced
helping
school
father
tea
stall
vadnagar
railway
station
age
modi
married
jashodaben
chimanlal
modi
abandoned
soon
first
publicly
acknowledged
wife
four
decade
later
required
indian
law
made
contact
since
modi
asserted
travelled
northern
india
two
year
leaving
parental
home
visiting
number
religious
centre
detail
travel
emerged
upon
return
gujarat
became
full
time
worker
r
state
emergency
declared
prime
minister
indira
gandhi
modi
went
hiding
r
assigned
bjp
held
several
position
within
party
hierarchy
rising
rank
general
secretary
c
modi
appointed
chief
minister
gujarat
due
keshubhai
patel
failing
health
poor
public
image
following
earthquake
bhuj
modi
elected
legislative
assembly
soon
administration
considered
complicit
gujarat
riot
people
killed
three
quarter
muslim
otherwise
criticised
management
crisis
special
investigation
team
appointed
supreme
court
india
found
evidence

In [19]:
## applying stopword on entire document
import re
for i in range(len(sentance)):
    review = re.sub('[^a-zA-Z]',' ',sentance[i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [22]:
corpus

[' modi was born and raised in vadnagar in northeastern gujarat  where he completed his secondary education ',
 'he was introduced to the rss at age eight ',
 'he has reminisced about helping out after school at his father s tea stall at the vadnagar railway station ',
 'at age     modi was married to jashodaben chimanlal modi  whom he abandoned soon after ',
 'he first publicly acknowledged her as his wife more than four decades later when required to do so by indian law  but has made no contact with her since ',
 'modi has asserted he had travelled in northern india for two years after leaving his parental home  visiting a number of religious centres  but few details of his travels have emerged ',
 'upon his return to gujarat in       he became a full time worker for the rss ',
 'after the state of emergency was declared by prime minister indira gandhi in       modi went into hiding ',
 'the rss assigned him to the bjp in      and he held several positions within the party hierarchy 

In [23]:
## bag of model
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
bag_count = CountVectorizer(binary=True)
x=bag_count.fit_transform(corpus)

In [25]:
x[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0]], d

In [27]:
## TF-IDF MODEL TRAINING
from sklearn.feature_extraction.text import TfidfVectorizer
tf_vec = TfidfVectorizer()
x=tf_vec.fit_transform(corpus)

In [29]:
x[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.20037006, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.29354046,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.29354046, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [30]:
## word to vec train
!pip install gensim

In [31]:
import gensim

In [32]:
from gensim.models import word2vec,keyedvectors

In [34]:
import gensim.downloader as api

In [36]:
word_vec=api.load('word2vec-google-news-300')

In [38]:
word_vec['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [39]:
word_vec['ram']

array([ 1.58203125e-01,  3.82812500e-01, -1.94335938e-01, -2.03125000e-01,
       -1.25732422e-02,  5.41687012e-04, -3.41796875e-02,  3.08593750e-01,
        5.41992188e-02,  1.87500000e-01, -1.25976562e-01, -1.77734375e-01,
       -1.22558594e-01,  2.02148438e-01, -1.24511719e-01, -5.29785156e-02,
       -2.03125000e-01,  2.37304688e-01,  1.01318359e-02, -3.65234375e-01,
        2.53906250e-01,  2.41210938e-01,  4.10156250e-02, -8.44726562e-02,
        4.51660156e-02, -7.42187500e-02, -8.49609375e-02,  1.15234375e-01,
        2.85156250e-01, -2.02148438e-01,  1.51367188e-01,  2.87109375e-01,
        4.10156250e-02,  1.71661377e-03, -7.38525391e-03, -2.90527344e-02,
        2.01225281e-04, -3.19824219e-02,  5.66406250e-02, -1.88476562e-01,
        4.98046875e-02,  1.93359375e-01,  2.33398438e-01,  4.15039062e-02,
       -1.28906250e-01,  4.90722656e-02,  6.59179688e-02,  1.91650391e-02,
        8.93554688e-02, -1.66992188e-01, -3.80859375e-01,  1.14746094e-01,
        2.91015625e-01, -

In [40]:
king_vec=word_vec['king']

In [41]:
word_vec.similarity('king','queen')

0.6510957